package packers // import "github.com/pinterb/namegen/pkg/packers"

import (
	"fmt"
	"math/rand"
	"strings"
)

var (
	left = [...]string{
		"admiring",
		"adoring",
		"affectionate",
		"agitated",
		"amazing",
		"angry",
		"awesome",
		"beautiful",
		"blissful",
		"bold",
		"boring",
		"brave",
		"busy",
		"charming",
		"clever",
		"cool",
		"compassionate",
		"competent",
		"condescending",
		"confident",
		"cranky",
		"crazy",
		"dazzling",
		"determined",
		"distracted",
		"dreamy",
		"eager",
		"ecstatic",
		"elastic",
		"elated",
		"elegant",
		"eloquent",
		"epic",
		"exciting",
		"fervent",
		"festive",
		"flamboyant",
		"focused",
		"friendly",
		"frosty",
		"funny",
		"gallant",
		"gifted",
		"goofy",
		"gracious",
		"great",
		"happy",
		"hardcore",
		"heuristic",
		"hopeful",
		"hungry",
		"infallible",
		"inspiring",
		"interesting",
		"intelligent",
		"jolly",
		"jovial",
		"keen",
		"kind",
		"laughing",
		"loving",
		"lucid",
		"magical",
		"mystifying",
		"modest",
		"musing",
		"naughty",
		"nervous",
		"nice",
		"nifty",
		"nostalgic",
		"objective",
		"optimistic",
		"peaceful",
		"pedantic",
		"pensive",
		"practical",
		"priceless",
		"quirky",
		"quizzical",
		"recursing",
		"relaxed",
		"reverent",
		"romantic",
		"sad",
		"serene",
		"sharp",
		"silly",
		"sleepy",
		"stoic",
		"strange",
		"stupefied",
		"suspicious",
		"sweet",
		"tender",
		"thirsty",
		"trusting",
		"unruffled",
		"upbeat",
		"vibrant",
		"vigilant",
		"vigorous",
		"wizardly",
		"wonderful",
		"xenodochial",
		"youthful",
		"zealous",
		"zen",
	}

	// Men who've played for the Green Bay Packers
	// https://en.wikipedia.org/wiki/List_of_Green_Bay_Packers_players
	packers = [...]string{
		"Abbrederis, Jared",
		"Aberson, Cliff",
		"Abrams, Nate",
		"Abramson, George",
		"Acks, Ron",
		"Adams, Chet",
		"Adams, Davante",
		"Adams, Montravius",
		"Adderley, Herb",
		"Adkins, Bob",
		"Affholter, Erik",
		"Afflis, William",
		"Agajanian, Ben",
		"Aguiar, Louie",
		"Aiyewa, Victor",
		"Akins, Chris",
		"Alcorn, Zac",
		"Aldridge, Ben",
		"Aldridge, Lionel",
		"Alexander, Jaire",
		"Allen, Kenderick",
		"Allerman, Kurt",
		"Allison, Geronimo",
		"Amos, Adrian",
		"Amsler, Marty",
		"Amundsen, Norm",
		"Anderson, Aric",
		"Anderson, Bill",
		"Anderson, Donny",
		"Anderson, John",
		"Anderson, Marques",
		"Anderson, Vickey Ray",
		"Andruzzi, Joe",
		"Ane, Charlie",
		"Apsit, Marger",
		"Archambeau, Lester",
		"Ard, Billy",
		"Ariey, Mike",
		"Arnold, Jahine",
		"Arthur, Mike",
		"Artmore, Rodney",
		"Ashmore, Marion",
		"Askson, Bert",
		"Atkins, Steve",
		"Auer, Todd",
		"Austin, Hise",
		"Avery, Steve",
		"Aydelette, Buddy",
		"Barclay, Don",
		"Barrington, Sam",
		"Bailey, Byron",
		"Bailey, Karsten",
		"Bain, Bill",
		"Baker, Frank",
		"Baker, Roy",
		"Balasz, Frank",
		"Baldwin, Al",
		"Banet, Herb",
		"Banjo, Chris",
		"Barber, Bob",
		"Barbre, Allen",
		"Barker, Bryan",
		"Barker, Roy",
		"Barnes, Emery",
		"Barnes, Gary",
		"Barnett, Nick",
		"Barnett, Solon",
		"Barragar, Nate",
		"Barrett, Jan",
		"Barrie, Sebastian",
		"Barry, Al",
		"Barry, Kevin",
		"Barry, Norm",
		"Barton, Don",
		"Bartrum, Mike",
		"Barzilauskas, Carl",
		"Basing, Myrt",
		"Basinger, Michael",
		"Baxter, Lloyd",
		"Beach, Sanjay",
		"Beck, Ken",
		"Becker, Wayland",
		"Bedell, Brad",
		"Beebe, Don",
		"Beekley, Bruce",
		"Bell, Albert",
		"Bell, Byron",
		"Bell, Chris",
		"Bell, Ed",
		"Bell, Kahlil",
		"Bell, Tyrone",
		"Bennett, Earl",
		"Bennett, Edgar",
		"Bennett, Martellus",
		"Bennett, Tony",
		"Berezney, Paul",
		"Berrang, Ed",
		"Berry, Connie Mack",
		"Berry, Ed",
		"Berry, Gary",
		"Bettencourt, Larry",
		"Bettis, Tom",
		"Beverly, David",
		"Bidwell, Josh",
		"Bieberstein, Adolph",
		"Biegel, Vince",
		"Bigby, Atari",
		"Bilda, Dick",
		"Billups, Lewis",
		"Biolo, John",
		"Birney, Tom",
		"Bishop, Desmond",
		"Blackmon, Roosevelt",
		"Blackmon, Will",
		"Blackshear, Jeff",
		"Blaine, Ed",
		"Blair, Michael",
		"Bland, Carl",
		"Bloodgood, Elbert",
		"Bodiford, Shaun",
		"Boedeker, Bill",
		"Boerio, Chuck",
		"Bolden, Juran",
		"Bolston, Conrad",
		"Bolton, Scott",
		"Bone, Warren",
		"Bono, Steve",
		"Booker, Vaughn",
		"Bookout, Billy",
		"Boone, J.R.",
		"Borak, Fred",
		"Borden, Nate",
		"Borgognone, Dirk",
		"Bowdoin, Jim",
		"Bowen, Matt",
		"Bowens, David",
		"Bowman, Ken",
		"Boyarsky, Jerry",
		"Boyd, Elmo",
		"Boyd, Greg",
		"Boykin, Jarrett",
		"Bracken, Don",
		"Bradley, Dave",
		"Bardley, Hunter",
		"Brady, Jeff",
		"Braggs, Byron",
		"Branstetter, Kent",
		"Bratkowski, Zeke",
		"Bray, Ray",
		"Breen, Gene",
		"Brennan, John",
		"Brice, Kentrell",
		"Brock, Charley",
		"Brock, Lou",
		"Brock, Matt",
		"Brockington, John",
		"Brooks, Barrett",
		"Brooks, Bucky",
		"Brooks, Robert",
		"Bross, Mal",
		"Broussard, Steve",
		"Brown, Aaron",
		"Brown, Allen",
		"Brown, Bob",
		"Brown, Buddy",
		"Brown, Carlos",
		"Brown, Dave",
		"Brown, Gary",
		"Brown, Gilbert",
		"Brown, Jonathan",
		"Brown, Ken",
		"Brown, Robert",
		"Brown, Timmy",
		"Brown, Tom",
		"Brown, Tony",
		"Browner, Ross",
		"Bruder, Hank",
		"Brunell, Mark",
		"Bucchianeri, Mike",
		"Buchanon, Willie",
		"Buck, Howard",
		"Buckley, Terrell",
		"Buhler, Larry",
		"Buland, Walt",
		"Bullough, Hank",
		"Bultman, Art",
		"Burgess, Ronnie",
		"Burnett, Morgan",
		"Burnette, Reggie",
		"Burris, Paul",
		"Burrow, Curtis",
		"Burrow, Jim",
		"Bush, Blair",
		"Bush, Jarrett",
		"Butler, Bill",
		"Butler, Frank",
		"Butler, LeRoy",
		"Butler, Mike",
		"Byrd, Emanuel",
		"Cade, Mossy",
		"Caffey, Lee Roy",
		"Cahoon, Tiny",
		"Caldwell, David",
		"Callahan, Joe",
		"Campbell, Rich",
		"Campen, James",
		"Canadeo, Tony",
		"Cannava, Al",
		"Cannon, Mark",
		"Capp, Dick",
		"Capuzzi, Jim",
		"Carey, Joe",
		"Carlson, Wes",
		"Carmichael, Al",
		"Carpenter, Lew",
		"Carr, Fred",
		"Carreker, Alphonso",
		"Carroll, Ahmad",
		"Carroll, Leo",
		"Carruth, Paul Ott",
		"Carter, Carl",
		"Carter, Jim",
		"Carter, Joe",
		"Carter, Mike",
		"Carter, Tony",
		"Casper, Cy",
		"Cassidy, Ron",
		"Cecil, Chuck",
		"Chandler, Don",
		"Chatman, Antonio",
		"Cheek, Louis",
		"Cherry, Bill",
		"Chesley, Francis",
		"Childs, Henry",
		"Chillar, Brandon",
		"Chmura, Mark",
		"Choate, Putt",
		"Christman, Paul",
		"Cifelli, Gus",
		"Cifers, Bob",
		"Clancy, Jack",
		"Clanton, Chuck",
		"Claridge, Dennis",
		"Clark, Allan",
		"Clark, Greg",
		"Clark, Jessie",
		"Clark, Kenny",
		"Clark, Michael",
		"Clark, Vinnie",
		"Clavelle, Shannon",
		"Clayton, Mark",
		"Clemens, Bob",
		"Clemens, Cal",
		"Clemons, Ray",
		"Clifton, Chad",
		"Clinton-Dix, Ha Ha",
		"Cloud, Jack",
		"Cobb, Randall",
		"Cobb, Reggie",
		"Cody, Ed",
		"Coffey, Junior",
		"Coffman, Paul",
		"Cole, Colin",
		"Coleman, Keo",
		"Coleman, Lavon",
		"Colledge, Daryn",
		"Collier, Steve",
		"Collins, Albin",
		"Collins, Bobby",
		"Collins, Brett",
		"Collins, Mark",
		"Collins, Nick",
		"Collins, Patrick",
		"Collins, Shawn",
		"Combs, Derek",
		"Comp, Irv",
		"Compton, Chuck",
		"Comstock, Rudy",
		"Concannon, Jack",
		"Cone, Fred",
		"Conway, Brett",
		"Cook, James",
		"Cook, Kelly",
		"Cook, Ted",
		"Cooke, Bill",
		"Cooks, Kerry",
		"Cooney, Mark",
		"Copeland, Russell",
		"Corker, John",
		"Coston, Junius",
		"Coughlin, Frank",
		"Coutre, Larry",
		"Cox, Ron",
		"Crabtree, Tom",
		"Craig, Larry",
		"Crawford, Keith",
		"Cremer, Ted",
		"Crenshaw, Leon",
		"Crimmins, Bernie",
		"Crockett, John",
		"Croft, Milburn",
		"Cronin, Tommy",
		"Crosby, Mason",
		"Croston, Dave",
		"Crouse, Ray",
		"Crowley, Jim",
		"Crutcher, Tommy",
		"Cuff, Ward",
		"Culbreath, Jim",
		"Culver, Al",
		"Culver, Tyrone",
		"Cumby, George",
		"Curcio, Mike",
		"Currie, Dan",
		"Curry, Bill",
		"Curry, Scott",
		"Cvercko, Andy",
		"Cyre, Hec",
		"DOnofrio, Mark",
		"Dahms, Tom",
		"Dale, Carroll",
		"Danelo, Joe",
		"Daniell, Ave",
		"Danjean, Ernie",
		"Darkins, Chris",
		"Darling, Bernard",
		"Davenport, Bill",
		"Davenport, Najeh",
		"Davey, Don",
		"Davidson, Ben",
		"Davis, Anthony",
		"Davis, Dave",
		"Davis, Harper",
		"Davis, Kenneth",
		"Davis, Pahl",
		"Davis, Ralph",
		"Davis, Rob",
		"Davis, Tyrone",
		"Davis, Willie",
		"Dawson, Dale",
		"Dawson, Gib",
		"DeLisle, Jim",
		"DeLuca, Tony",
		"Dean, Walter",
		"Deeks, Don",
		"Dees, Bob",
		"Degrate, Tony",
		"Del Gaizo, Jim",
		"Del Greco, Al",
		"Dellenbach, Jeff",
		"Dendy, Patrick",
		"Dennard, Preston",
		"Dent, Burnell",
		"Deschaine, Dick",
		"Detmer, Ty",
		"DiPierro, Ray",
		"Dickey, Lynn",
		"Didier, Clint",
		"Dietrich-Smith, Evan",
		"Diggs, Nail",
		"Dillon, Bobby",
		"Dilweg, Anthony",
		"Dilweg, Lavern",
		"Dimler, Rich",
		"Dingle, Antonio",
		"Disend, Leo",
		"Dittrich, John",
		"Don Carlos, Waldo",
		"Donohoe, Mike",
		"Dorleant, Makinton",
		"Dorsett, Matthew",
		"Dorsey, Dean",
		"Dorsey, John",
		"Dotson, Earl",
		"Dotson, Santana",
		"Douglass, Bobby",
		"Douglass, Mike",
		"Dowden, Corey",
		"Dowden, Steve",
		"Dowler, Boyd",
		"Dowling, Brian",
		"Drechsler, Dave",
		"Dreyer, Wally",
		"Driver, Donald",
		"Drost, Jeff",
		"Drulis, Chuck",
		"DuMoe, Bill",
		"Duckett, Forey",
		"Duford, Wilfred",
		"Duhart, Paul",
		"Dukes, Jamie",
		"Dunaway, Dave",
		"Duncan, Ken",
		"Dunn, Joseph &quot;Red&quot;",
		"Dunnigan, Pat",
		"Earp, Jug",
		"Eason, Roy",
		"Ecker, Enrique",
		"Edwards, Antuan",
		"Edwards, Earl",
		"Ellerson, Gary",
		"Elliott, Carlton",
		"Elliott, Jayrone",
		"Elliott, Tony F.",
		"Ellis, Gerry",
		"Ellis, Ken",
		"Enderle, Dick",
		"Engebretsen, Paul",
		"Engelmann, Wuert",
		"Enright, Rex",
		"Epps, Phil",
		"Estep, Mike",
		"Ethridge, Joe",
		"Evans, Dick",
		"Evans, Doug",
		"Evans, Jack",
		"Evans, Lon",
		"Falkenstein, Tony",
		"Fanucci, Mike",
		"Faverty, Hal",
		"Favre, Brett",
		"Faye, Allen",
		"Feasel, Greg",
		"Feathers, Beattie",
		"Ferguson, Howie",
		"Ferguson, Robert",
		"Ferragamo, Vince",
		"Ferrario, Bill",
		"Ferry, Lou",
		"Fields, Angelo",
		"Finley, Jermichael",
		"Finnin, Tom",
		"Fisher, Tony",
		"Fitzgerald, Kevin",
		"Fitzgibbons, Paul",
		"Flaherty, Dick",
		"Flanagan, Mike",
		"Flanigan, Jim",
		"Fleming, Marv",
		"Flinn, Ryan",
		"Flowers, Bob",
		"Floyd, Bobby Jack",
		"Flynn, Matt",
		"Flynn, Tom",
		"Folkins, Lee",
		"Fontenot, Herman",
		"Fontenot, Therrian",
		"Ford, Len",
		"Forester, Bill",
		"Forte, Aldo",
		"Forte, Bob",
		"Francies, Chris",
		"Francis, Joe",
		"Francois, Robert",
		"Frankowski, Ray",
		"Franks, Bubba",
		"Franta, Herb",
		"Franz, Nolan",
		"Franz, Todd",
		"Frase, Paul",
		"Freeman, Antonio",
		"Freeman, Bobby",
		"Fries, Sherwood",
		"Fritsch, Ted",
		"Frutig, Ed",
		"Fuller, Curtis",
		"Fuller, Joe",
		"Fullwood, Brent",
		"Fusina, Chuck",
		"Gabbard, Steve",
		"Gado, Samkon",
		"Galbraith, Scott",
		"Galbreath, Harry",
		"Gantenbein, Milt",
		"Garcia, Eddie",
		"Gardella, Gus",
		"Gardner, Milton",
		"Gardner, Rod",
		"Garrett, Bobby",
		"Garrett, Len",
		"Gassert, Ron",
		"Gatewood, Lester",
		"Gavin, Buck",
		"Gaydos, Kent",
		"Gbaja-Biamila, Kabeer",
		"Getty, Charlie",
		"Gibson, Paul",
		"Gillette, Jim",
		"Gillingham, Gale",
		"Gillus, Willie",
		"Giordano, Matt",
		"Girard, Earl",
		"Gizzi, Chris",
		"Glass, Leland",
		"Glenn, Terry",
		"Glick, Ed",
		"Gofourth, Derrel",
		"Goldenberg, Charles",
		"Goode, Brett",
		"Goodman, Herbert",
		"Goodman, Les",
		"Goodson, Demetri",
		"Goodnight, Clyde",
		"Gordon, Darrien",
		"Gordon, Dick",
		"Gordon, Lou",
		"Gordy, Josh",
		"Gorgal, Ken",
		"Grabowski, Jim",
		"Graham, Jay",
		"Graham, Jimmy",
		"Grant, David",
		"Grant, Ryan",
		"Gray, Cecil",
		"Gray, Jack",
		"Gray, Johnnie",
		"Green, Ahman",
		"Green, Alex",
		"Green, Jessie",
		"Greene, Tiger",
		"Greeney, Norm",
		"Greenfield, Tom",
		"Greenwood, David",
		"Gregg, Forrest",
		"Gremminger, Hank",
		"Griffen, Hal",
		"Grimes, Billy",
		"Grimm, Dan",
		"Gros, Earl",
		"Grove, Roger",
		"Gruber, Bob",
		"Gueno, Jim",
		"Guion, Letroy",
		"Hackbart, Dale",
		"Hackett, Joey",
		"Haddix, Michael",
		"Hadl, John",
		"Haley, Darryl",
		"Hall, Charlie",
		"Hall, Korey",
		"Hall, Lamont",
		"Hall, Mark",
		"Hallstrom, Ron",
		"Hamilton, Ruffin",
		"Hampton, Dave",
		"Hanner, Dave",
		"Hanny, Frank",
		"Hansen, Don",
		"Hansen, Hal",
		"Hanson, Chris",
		"Harden, Derrick",
		"Harden, Leon",
		"Harding, Roger",
		"Hardy, Kevin",
		"Hargrove, Jimmy",
		"Harper, Chris",
		"Harrell, Graham",
		"Harrell, Justin",
		"Harrell, Willard",
		"Harris, Al",
		"Harris, Bernardo",
		"Harris, Corey",
		"Harris, Jack",
		"Harris, Jackie",
		"Harris, Leotis",
		"Harris, Raymont",
		"Harris, Tim",
		"Harris, William",
		"Harrison, Anthony",
		"Hart, Doug",
		"Hartnett, Perry",
		"Hartwig, Keith",
		"Harvey, Maurice",
		"Hasselbeck, Matt",
		"Hathcock, Dave",
		"Hauck, Tim",
		"Havig, Dennis",
		"Hawk, A.J.",
		"Hawkins, Mike",
		"Hawthorne, Michael",
		"Haycraft, Ken",
		"Hayden, Aaron",
		"Hayes, Chris",
		"Hayes, Dave",
		"Hayes, Gary",
		"Hayes, Norbert",
		"Hayhoe, Bill",
		"Hays, George",
		"Hayward, Casey",
		"Hearden, Lester",
		"Hearden, Tom",
		"Heath, Stan",
		"Hefner, Larry",
		"Heimburger, Craig",
		"Held, Paul",
		"Helluin, Jerry",
		"Henderson, William",
		"Hendrian, Dutch",
		"Hendricks, Ted",
		"Henry, Urban",
		"Hentrich, Craig",
		"Herber, Arnie",
		"Herron, Noah",
		"Hickman, Larry",
		"Highsmith, Don",
		"Hill, Don",
		"Hill, Jim",
		"Hill, Nate",
		"Hilton, John",
		"Himes, Dick",
		"Hinkle, Clarke",
		"Hinte, Hal",
		"Hobbins, Jim",
		"Hodge, Abdul",
		"Hoffman, Gary",
		"Holiday, Carlyle",
		"Holland, Darius",
		"Holland, Johnny",
		"Holler, Ed",
		"Holliday, Vonnie",
		"Hollinquest, Lamont",
		"Holmberg, Rob",
		"Holmes, Darick",
		"Holmes, Jerry",
		"Hood, Estus",
		"Hope, Charles",
		"Horn, Don",
		"Hornung, Paul",
		"Horton, Jason",
		"Houston, Bobby",
		"Howard, Desmond",
		"Howard, Tubby",
		"Howell, John",
		"Howton, Billy",
		"Hubbard, Cal",
		"Huckleby, Harlan",
		"Hudson, Bob",
		"Huffman, Tim",
		"Hull, Tom",
		"Humphrey, Donnie",
		"Humphrey, Tory",
		"Hundley, Brett",
		"Hunt, Cletidus",
		"Hunt, Ervin",
		"Hunt, Kevin",
		"Hunt, Mike",
		"Hunter, Art",
		"Hunter, Jason",
		"Hunter, Scott",
		"Hunter, Tony",
		"Hutchins, Paul",
		"Hutson, Don",
		"Hyde, Micah",
		"Hyland, Bob",
		"Ilkin, Tunch",
		"Iman, Ken",
		"Ingalls, Robert",
		"Ingram, Darryl",
		"Ingram, Mark",
		"Isbell, Cecil",
		"Ivery, Eddie Lee",
		"Jacke, Chris",
		"Jackson, Alcender",
		"Jackson, Brandon",
		"Jackson, Chris",
		"Jackson, Don",
		"Jackson, Grady",
		"Jackson, James",
		"Jackson, Johnnie",
		"Jackson, Keith",
		"Jackson, Melvin",
		"Jacobs, Allen",
		"Jacobs, Jack",
		"Jacunski, Harry",
		"Jakes, Van",
		"James, Claudis",
		"Janet, Ernie",
		"Janis, Jeff",
		"Jankowski, Ed",
		"Jansante, Val",
		"Jay, Craig",
		"Jefferson, John",
		"Jefferson, Norman",
		"Jenke, Noel",
		"Jenkins, Billy",
		"Jenkins, Cullen",
		"Jennings, Greg",
		"Jennings, Jim",
		"Jennings, M. D.",
		"Jennison, Ray",
		"Jensen, Greg",
		"Jensen, Jim",
		"Jervey, Travis",
		"Jeter, Bob",
		"John, Ulrick",
		"Johnson, Bill",
		"Johnson, Charles",
		"Johnson, Daniel",
		"Johnson, Ezra",
		"Johnson, Glenn",
		"Johnson, Howard",
		"Johnson, Joe",
		"Johnson, Joe",
		"Keshon, Johnson",
		"Johnson, LeShon",
		"Johnson, Marvin",
		"Johnson, Quinn",
		"Johnson, Randy",
		"Johnson, Reggie",
		"Johnson, Sammy",
		"Johnson, Tom",
		"Johnston, Chester",
		"Jolly, Johnny",
		"Jolly, Mike",
		"Jones, Aaron",
		"Jones, Bobby",
		"Jones, Boyd",
		"Jones, Bruce",
		"Jones, Calvin",
		"Jones, Daryll",
		"Jones, Jamal",
		"Jones, James",
		"Jones, Ron",
		"Jones, Scott",
		"Jones, Sean",
		"Jones, Terry",
		"Jones, Tom",
		"Charles Jordan",
		"Jordan, Henry",
		"Jordan, Ken",
		"Jorgensen, Carl",
		"Josue, Steve",
		"Joyner, Seth",
		"Jue, Bhawoh",
		"Jurkovic, John",
		"Kahler, Bob",
		"Kell, Paul",
		"Kelley, Bill",
		"Kelly, Joe",
		"Kemp, Perry",
		"Kendricks, Lance",
		"Kercher, Bob",
		"Kern, Bill",
		"Kerridge, Joe",
		"Keuper, Ken",
		"Kiel, Blair",
		"Kiesling, Walt",
		"Kight, Kelvin",
		"Kilbourne, Warren",
		"Kimball, Bobby",
		"Kimmel, J. D.",
		"Kinard, Billy",
		"Kinder, Randy",
		"King, David",
		"King, Don",
		"King, Don",
		"King, Kevin",
		"Kirby, Jack",
		"Kitson, Syd",
		"Kitts, Jim",
		"Kizer, DeShone",
		"Klaus, Fee",
		"Klemm, Adrian",
		"Kliebhan, Adolph",
		"Knafelc, Gary",
		"Knapp, Lindsay",
		"Knutson, Gene",
		"Knutson, Steve",
		"Koart, Matt",
		"Koch, Greg",
		"Koncar, Mark",
		"Konopasek, Ed",
		"Koonce, George",
		"Kopay, Dave",
		"Kostelnik, Ron",
		"Kotal, Eddie",
		"Kovatch, John",
		"Kowalkowski, Bob",
		"Kramer, Jerry",
		"Kramer, Ron",
		"Kranz, Ken",
		"Krause, Larry",
		"Krause, Ryan",
		"Kroll, Bob",
		"Kuberski, Bob",
		"Kuechenberg, Rudy",
		"Kuhn, John",
		"Kumerow, Jake",
		"Kurth, Joe",
		"Kuusisto, Bill",
		"Lacy, Eddie",
		"Ladrow, Wally",
		"Lally, Bob",
		"Lambeau, Curly",
		"Lammons, Pete",
		"Landers, Walt",
		"Landeta, Sean",
		"Lane, MacArthur",
		"Lang, T. J.",
		"Lankas, Jim",
		"Larson, Bill",
		"Larson, Fred",
		"Larson, Kurt",
		"Laslavic, Jim",
		"Lathrop, Kit",
		"Lauer, Dutch",
		"Lauer, Larry",
		"Laughlin, Jim",
		"Lawrence, Jim",
		"Laws, Joe",
		"LeJeune, Walt",
		"Leach, Vonta",
		"Leake, John",
		"Leaper, Wes",
		"Lee, Bill",
		"Lee, Charles",
		"Lee, Donald",
		"Lee, James",
		"Lee, Mark",
		"Lee, Pat",
		"Lee, ReShard",
		"Leigh, Charlie",
		"Leiker, Tony",
		"Lenon, Paris",
		"Leopold, Bobby",
		"Lester, Darrell",
		"Letlow, Russ",
		"Levens, Dorsey",
		"Lewellen, Verne",
		"Lewis, Cliff",
		"Lewis, Gary",
		"Lewis, Mark",
		"Lewis, Mike",
		"Lewis, Ron",
		"Lewis, Tim",
		"Lidberg, Cully",
		"Light, Alex",
		"Lipscomb, Paul",
		"Little, Earl",
		"Linsley, Corey",
		"Livingston, Dale",
		"Lofton, James",
		"Logan, Dave",
		"Logan, Dick",
		"Lollar, Slick",
		"London, Antonio",
		"Long, Bob",
		"Longwell, Ryan",
		"Loomis, Ace",
		"Losch, Jack",
		"Lovato, Rick",
		"Lowry, Dean",
		"Lucas, Chad",
		"Luchey, Nick",
		"Lucky, Bill",
		"Lueck, Bill",
		"Luhn, Nolan",
		"Luke, Steve",
		"Lusteg, Booth",
		"Lyle, Dewey",
		"Lyman, Del",
		"Lyon, Billy",
		"Maas, Bill",
		"MacLeod, Tom",
		"Mack, Red",
		"Maddox, George",
		"Majkowski, Don",
		"Malancon, Rydell",
		"Malone, Grover",
		"Mandarich, Tony",
		"Mandeville, Chris",
		"Manley, Leon",
		"Mann, Bob",
		"Mann, Erroll",
		"Manning, Brian",
		"Manning, Roy",
		"Manning, Terrell",
		"Mansfield, Von",
		"Manuel, Marquand",
		"Marcol, Chester",
		"Marks, Larry",
		"Marshall, Bud",
		"Marshall, Torrance",
		"Herman, Martell",
		"Martin, Charles",
		"Martin, David",
		"Martin, Derrick",
		"Martin, Ingle",
		"Martin, Ruvell",
		"Martinez, Blake",
		"Martinkovic, John",
		"Maryland, Russell",
		"Mason, Dave",
		"Mason, Joel",
		"Mason, Larry",
		"Massey, Carlton",
		"Masters, Norm",
		"Masthay, Tim",
		"Mataele, Stan",
		"Mathys, Charlie",
		"Matson, Pat",
		"Matthews, Al",
		"Matthews, Aubrey",
		"Matthews III, Clay",
		"Mattos, Harry",
		"Matuszak, Marv",
		"Mayer, Frank",
		"Mayes, Derrick",
		"Mays, Devante",
		"Mays, Kivuusama",
		"McAuliffe, Jack",
		"McBride, Ron",
		"McBride, Tod",
		"McCaffrey, Bob",
		"McCarren, Larry",
		"McCaslin, Eugene",
		"McCloughan, Dave",
		"McConkey, Phil",
		"McCoy, Mike",
		"McCoy, Mike",
		"McCrary, Herdis",
		"McCray, Justin",
		"McDonald, Dustin",
		"McDougal, Bob",
		"McDowell, John",
		"McElmurry, Blaine",
		"McGarrahan, Scott",
		"McGarry, John",
		"McGaw, Walt",
		"McGeary, Clarence",
		"McGee, Buford",
		"McGee, Max",
		"McGeorge, Rich",
		"McGill, Lenny",
		"McGrew, Sylvester",
		"McGruder, Mike",
		"McGuire, Gene",
		"McHan, Lamar",
		"McHugh, Sean",
		"McIlhenny, Don",
		"McIntyre, Guy",
		"McJulien, Paul",
		"McKay, Roy",
		"McKenzie, Keith",
		"McKenzie, Mike",
		"McKenzie, Raleigh",
		"McLaughlin, Joe",
		"McLaughlin, Lee",
		"McLean, Ray",
		"McLeod, Mike",
		"McMahon, Jim",
		"McMath, Herb",
		"McMichael, Steve",
		"McMillan, Ernie",
		"McMillian, Jerron",
		"McNabb, Dexter",
		"McNally, John",
		"McPherson, Forrest",
		"Meade, Mike",
		"Mealey, Rondell",
		"Meilinger, Steve",
		"Melka, James",
		"Mendoza, Ruben",
		"Mercein, Chuck",
		"Mercer, Mike",
		"Merrill, Casey",
		"Merrill, Mark",
		"Merriweather, Mike",
		"Mestnik, Frank",
		"Metcalf, Eric",
		"Meyer, Craig",
		"Michaels, Lou",
		"Michaels, Walt",
		"Michalske, Mike",
		"Michels, John",
		"Mickens, Terry",
		"Middleton, Terdell",
		"Midler, Lou",
		"Mihajlovich, Lou",
		"Milan, Don",
		"Millard, Keith",
		"Miller, Don",
		"Miller, John",
		"Miller, John",
		"Miller, Ookie",
		"Miller, Paul",
		"Miller, Tom",
		"Mills, Stan",
		"Minick, Paul",
		"Miree, Brandon",
		"Mitchell, Basil",
		"Mitchell, Charlie",
		"Mitchell, Roland",
		"Moffitt, Mike",
		"Moje, Dick",
		"Molenda, Bo",
		"Moll, Tony",
		"Monaco, Ron",
		"Monnett, Bob",
		"Monroe, Henry",
		"Montgomery, Michael",
		"Montgomery, Ty",
		"Moore, Allen",
		"Moore, Blake",
		"Moore, Brent",
		"Moore, Jason",
		"Moore, Rich",
		"Moore, Tom",
		"Moran, Rich",
		"Morency, Vernand",
		"Moresco, Tim",
		"Morgan, Anthony",
		"Morris, Jim Bob",
		"Morris, Larry",
		"Morris, Lee",
		"Morrison, Antonio",
		"Morrissey, Jim",
		"Morton, Mike",
		"Moselle, Dom",
		"Moses, Dezman",
		"Moses, J. J.",
		"Mosley, Russ",
		"Moss, Perry",
		"Mott, Joe",
		"Mott, Buster",
		"Muir, Daniel",
		"Mullen, Roderick",
		"Mulleneaux, Carl",
		"Mulleneaux, Lee",
		"Murphy, Mark",
		"Murphy, Terrence",
		"Murray, Jab",
		"Nadolney, Romanus",
		"Nall, Craig",
		"Nash, Tom",
		"Navies, Hannibal",
		"Neal, Ed",
		"Neal, Frankie",
		"Neal, Mike",
		"Neill, Bill",
		"Nelson, Bob",
		"Nelson, Jordy",
		"Nelson, Jim",
		"Neville, Tom",
		"Newhouse, Marshall",
		"Newsome, Craig",
		"Nichols, Hamilton",
		"Nickerson, Hardy",
		"Niemann, Walter",
		"Nitschke, Ray",
		"Nix, Doyle",
		"Nixon, Fred",
		"Nixon, James",
		"Noble, Brian",
		"Noonan, Danny",
		"Norgard, Al",
		"Norton, Jerry",
		"Norton, Marty",
		"Norton, Rick",
		"Nussbaumer, Bob",
		"Nuzum, Rick",
		"Nwokorie, Chukie",
		"Nystrom, Lee",
		"OBoyle, Harry",
		"OConnor, Bob",
		"ODonahue, Pat",
		"ODonnell, Richard",
		"OMalley, Tom",
		"ONeal, Andre",
		"ONeil, Ed",
		"OSteen, Dwayne",
		"OSullivan, J. T.",
		"Oates, Brad",
		"Oats, Carleton",
		"Odom, Chris",
		"Odom, Steve",
		"Odson, Urban",
		"Oglesby, Alfred",
		"Ohlgren, Earl",
		"Okoniewski, Steve",
		"Oliver, Muhammad",
		"Olsen, Ralph",
		"Olsonoski, Larry",
		"Orlich, Dan",
		"Osborn, Dave",
		"Owens, Rip",
		"Palmer, Tony",
		"Palumbo, Sam",
		"Pankey, Adam",
		"Pannell, Ernie",
		"Pape, Oran",
		"Papit, John",
		"Parilli, Babe",
		"Parker, De&#39;Mond",
		"Parker, Freddie",
		"Parlavecchio, Chet",
		"Paskett, Keith",
		"Paskvan, George",
		"Patrick, Frank",
		"Patrick, Lucas",
		"Patterson, Shawn",
		"Patton, Ricky",
		"Paulekas, Tony",
		"Paup, Bryce",
		"Payne, Ken",
		"Pearson, Lindy",
		"Peay, Francis",
		"Pederson, Doug",
		"Pelfrey, Ray",
		"Peppers, Julius",
		"Peprah, Charlie",
		"Perillo, Justin",
		"Perkins, Don",
		"Perko, Tom",
		"Perry, Claude",
		"Perry, Nick",
		"Pesonen, Dick",
		"Peterson, Kenny",
		"Peterson, Les",
		"Peterson, Ray",
		"Petway, David",
		"Pickens, Bruce",
		"Pickett, Ryan",
		"Pisarkiewicz, Steve",
		"Pitts, Elijah",
		"Pitts, Ron",
		"Ploeger, Kurt",
		"Pointer, John",
		"Pope, Bucky",
		"Pope, P. J.",
		"Poppinga, Brady",
		"Powers, Sammy",
		"Prather, Guy",
		"Pregulman, Merv",
		"Prescott, Hal",
		"Preston, Roell",
		"Prior, Mike",
		"Pritko, Steve",
		"Prokop, Joe",
		"Provo, Fred",
		"Psaltis, Jim",
		"Purdy, Pid",
		"Pureifory, Dave",
		"Purnell, Frank",
		"Quarless, Andrew",
		"Quatse, Jess",
		"Query, Jeff",
		"Quinlan, Bill",
		"Radick, Ken",
		"Rafferty, Vince",
		"Raji, B. J.",
		"Randolph, Al",
		"Randolph, Terry",
		"Ranspot, Keith",
		"Rash, Lou",
		"Ray, Baby",
		"Rayner, Dave",
		"Redick, Cornelius",
		"Regnier, Pete",
		"Reichardt, Bill",
		"Reid, Floyd",
		"Renner, Bill",
		"Reynolds, Jamal",
		"Rhodemyre, Jay",
		"Rice, Allen",
		"Richard, Gary",
		"Riddick, Ray",
		"Ringo, Jim",
		"Ripkowski, Aaron",
		"Risher, Alan",
		"Rison, Andre",
		"Rivera, Marco",
		"Roach, John",
		"Robbins, Austin",
		"Robbins, Tootie",
		"Roberts, Bill",
		"Robinson, Bill",
		"Robinson, Charley",
		"Robinson, Dave",
		"Robinson, Eugene",
		"Robinson, Koren",
		"Robinson, Luther",
		"Robinson, Michael",
		"Robison, Tommy",
		"Roche, Alden",
		"Rodgers, Aaron",
		"Rodgers, Richard",
		"Rodgers, Del",
		"Rogers, Nick",
		"Rohrig, Herm",
		"Roller, Dave",
		"Roman, Mark",
		"Romine, Al",
		"Rosatti, Rudy",
		"Rose, Al",
		"Roskie, Ken",
		"Ross, Dan",
		"Rossum, Allen",
		"Rote, Tobin",
		"Rouse, Aaron",
		"Rowser, John",
		"Rubens, Larry",
		"Rubley, T. J.",
		"Rudzinski, Paul",
		"Ruegamer, Grey",
		"Ruettgers, Ken",
		"Ruetz, Howie",
		"Rule, Gordon",
		"Rush, Clive",
		"Ruzich, Steve",
		"Ryan, Jake",
		"Ryan, Jon",
		"Salem, Harvey",
		"Salsbury, Jim",
		"Sample, Chuck",
		"Sampson, Howard",
		"Sams, Ron",
		"Sander, B. J.",
		"Sandifer, Dan",
		"Sands, Terdell",
		"Sandusky, John",
		"Sarafiny, Al",
		"Satterfield, Brian",
		"Saturday, Jeff",
		"Sauer, George",
		"Saunders, Russ",
		"Scales, Hurles",
		"Schammel, Zud",
		"Scherer, Bernie",
		"Schlinkman, Walt",
		"Schmaehl, Art",
		"Schmidt, George",
		"Schmitt, John",
		"Schneidman, Herm",
		"Schoemann, Roy",
		"Schroeder, Bill",
		"Schroll, Bill",
		"Schuette, Carl",
		"Schuh, Harry",
		"Schuh, Jeff",
		"Schultz, Charles",
		"Schum, Jake",
		"Schwammel, Ade",
		"Scott, JK",
		"Scott, Patrick",
		"Scott, Randy",
		"Scribner, Bucky",
		"Secord, Joe",
		"Seeman, George",
		"Seibold, Champ",
		"Self, Clarence",
		"Serini, Wash",
		"Shanley, Jim",
		"Sharpe, Sterling",
		"Sharper, Darren",
		"Shelley, Deck",
		"Shield, Joe",
		"Shields, Sam",
		"Shirey, Fred",
		"Shumate, Mark",
		"Sikahema, Vai",
		"Simmons, Dave",
		"Simmons, John",
		"Simmons, Wayne",
		"Simpkins, Ron",
		"Simpson, Nate",
		"Simpson, Travis",
		"Sims, Joe",
		"Sitton, Josh",
		"Skaugstad, Daryle",
		"Skeate, Gil",
		"Skibinski, Joe",
		"Skinner, Gerald",
		"Skoglund, Bob",
		"Skoronski, Bob",
		"Slaughter, T. J.",
		"Sleight, Elmer",
		"Smith, Barry",
		"Smith, Barty",
		"Smith, Ben",
		"Smith, Blane",
		"Smith, Bruce",
		"Smith, Dave",
		"Smith, Donnell",
		"Smith, Earl",
		"Smith, Ed",
		"Smith, Wes",
		"Snelling, Ken",
		"Snider, Malcolm",
		"Snider, Matt",
		"SoOto, Vic",
		"Sorenson, Glen",
		"Spagnola, John",
		"Sparlis, Al",
		"Spears, Ron",
		"Spencer, Joe",
		"Spencer, Ollie",
		"Spilis, John",
		"Spinks, Jack",
		"Spitz, Jason",
		"Spriggs, Marcus",
		"Sproul, Dennis",
		"Stachowicz, Ray",
		"Staggers, Jon",
		"Stahlman, Dick",
		"Stanley, Walter",
		"Stansauk, Don",
		"Starch, Ken",
		"Starks, James",
		"Staroba, Paul",
		"Starr, Bart",
		"Starret, Ben",
		"Steele, Ben",
		"Steen, Frank",
		"Steiner, Rebel",
		"Stenerud, Jan",
		"Stephen, Scott",
		"Stephens, John",
		"Stephenson, Dave",
		"Sterling, John",
		"Stevens, Billy",
		"Stewart, Steve",
		"Stills, Ken",
		"Stokes, Barry",
		"Stokes, Tim",
		"Stonebraker, John",
		"Stoneburner, Jake",
		"Strickland, Fred",
		"Sturgeon, Lyle",
		"Sullivan, Carl",
		"Sullivan, John",
		"Summerhays, Bob",
		"Summers, Don",
		"Sutton, Mickey",
		"Svendsen, Earl",
		"Svendsen, George",
		"Swanke, Karl",
		"Swiney, Erwin",
		"Switzer, Veryl",
		"Sydney, Harry",
		"Symank, John",
		"Szafaryn, Len",
		"Tagge, Jerry",
		"Tassos, Damon",
		"Taugher, Claude",
		"Tauscher, Mark",
		"Aaron Taylor, Aaron",
		"Teague, George",
		"Temp, Jim",
		"Tenner, Bob",
		"Terrell, Pat",
		"Teteak, Deral",
		"Thierry, John",
		"Thomas, Ike",
		"Thomason, Jeff",
		"Thompson, Arland",
		"Thornburg, Jeremy",
		"Thurman, A",
		"Thurston, F",
		"Timberlake, G",
		"Timmerman, A",
		"Tinker, G",
		"Tinsley, P",
		"Toburen, N",
		"Tollefson, C",
		"Tolzien, S",
		"Tomczak, M",
		"Tomich, J",
		"Toner, T",
		"Tonnemaker, C",
		"Tonyan, R",
		"Torkelson, E",
		"Traylor, K",
		"Tretter, JC",
		"Tripp, J",
		"Troup, B",
		"Truluck, R-Kal",
		"Tuaolo, E",
		"Tullis, W",
		"Tunnell, E",
		"Turner, R",
		"Turpin, M",
		"Tuttle, G",
		"Twedell, F",
		"Uecker, Keith",
		"Underwood, Marviel",
		"Uram, Andy",
		"Urban, Alex",
		"Usher, Eddie",
		"Vairo, Dominic",
		"Van-Dyke, Bruce",
		"Van-Every, Hal",
		"Van-Roten, Greg",
		"Van-Sickle, Clyde",
		"Van-Valkenburg, Pete",
		"Vandersea, Phil",
		"Vanoy, Vernon",
		"Vant Hull, Fred",
		"Vataha, Randy",
		"Veingrad, Alan",
		"Verba, Ross",
		"Vereen, Carl",
		"Vergara, George",
		"Viaene, David",
		"Villanucci, Vince",
		"Vinson, Fred",
		"Vitale, Danny",
		"Vogds, Evan",
		"Vogel, Justin",
		"Voss, Lloyd",
		"Voss, Tillie",
		"Waddy, Jude",
		"Wade, Charlie",
		"Wafer, Carl",
		"Wagner, Bryan",
		"Wagner, Buff",
		"Wagner, Steve",
		"Wahle, Mike",
		"Walker, Cleo",
		"Walker, Frank",
		"Walker, Javon",
		"Walker, Josh",
		"Walker, Malcolm",
		"Walker, Randy",
		"Walker, Rod",
		"Walker, Sammy",
		"Walker, Val Joe",
		"Wallace, Calvin",
		"Wallace, Seneca",
		"Wallace, Taco",
		"Walls, Wesley",
		"Walsh, Ward",
		"Walter, Tyson",
		"Warren, Steve",
		"Washington, Chuck",
		"Waters, Herb",
		"Watts, Elbert",
		"Wayne, Nate",
		"Weathers, Clarence",
		"Weatherwax, Jim",
		"Weaver, Gary",
		"Webb, Chuck",
		"Webber, Dutch",
		"Webster, Tim",
		"Weddington, Mike",
		"Wehba, Ray",
		"Weigel, Lee",
		"Weisgerber, Dick",
		"Weishuhn, Clayton",
		"Wellman, Mike",
		"Wells, Don",
		"Wells, Scott",
		"Wells, Terry",
		"West, Ed",
		"West, Pat",
		"Westbrook, Bryant",
		"Wetnight, Ryan",
		"Wheeler, Cowboy",
		"Whitaker, Bill",
		"White, Adrian",
		"White, Chris",
		"White, Gene",
		"White, Reggie",
		"White, Tracy",
		"Whitehead, Jermaine",
		"Whitehurst, David",
		"Whitley, James",
		"Whittenton, Jesse",
		"Whitticker, William",
		"Wicks, Bob",
		"Widby, Ron",
		"Widell, Doug",
		"Wildung, Dick",
		"Wilkens, Elmer",
		"Wilkerson, Bruce",
		"Wilkerson, Muhammad",
		"Wilkins, Gabe",
		"Wilkins, Marcus",
		"Willhite, Kevin",
		"Williams, A. D.",
		"Williams, Brian",
		"Williams, Clarence",
		"Williams, Corey",
		"Williams, Delvin",
		"Williams, Gerald",
		"Williams, Howie",
		"Williams, Jamaal",
		"Williams, K. D.",
		"Williams, Kevin",
		"Williams, Mark",
		"Williams, Perry",
		"Williams, Tramon",
		"Williams, Travis",
		"Williams, Tyrone",
		"Williams, Walt",
		"Willig, Matt",
		"Willis, James",
		"Wilner, Jeff",
		"Wilson, Ben",
		"Wilson, Charles",
		"Wilson, Gene",
		"Wilson, Marcus",
		"Wilson, Milt",
		"Wilson, Mule",
		"Wilson, Ray",
		"Wimberly, Abner",
		"Wingle, Blake",
		"Wingo, Rich",
		"Winkler, Francis",
		"Winkler, Randy",
		"Winslow, Paul",
		"Winter, Blaise",
		"Winters, Chet",
		"Winters, Frank",
		"Winther, Wimpy",
		"Wishom, Jerron",
		"Wisne, Jerry",
		"Withrow, Cal",
		"Witte, Earl",
		"Wizbicki, Alex",
		"Wood, Bobby",
		"Wood, Willie",
		"Woodin, Howard",
		"Woods, Jerry",
		"Woodside, Keith",
		"Woodson, Charles",
		"Workman, Vince",
		"Worthy, Jerel",
		"Wortman, Keith",
		"Wright, Randy",
		"Wright, Steve",
		"Wuerffel, Danny",
		"Wunsch, Harry",
		"Wynn, DeShawn",
		"Wynn, Jarius",
		"Young, Billy",
		"Young, Glenn",
		"Young, Paul",
		"Zarnas, Gust",
		"Zatkoff, Roger",
		"Zeller, Joe",
		"Zendejas, Max",
		"Zeno, Lance",
		"Zimmerman, Don",
		"Zoll, D",
		"Zombo, Frank",
		"Zorn, Jim",
		"Zuidmulder, D",
		"Zuver, M",
	}
)

// GetRandomName generates a random name from the list of adjectives and surnames in this package
// formatted as "adjective-surname". For example 'focused-turing'. If retry is non-zero, a random
// integer between 0 and 10 will be added to the end of the name, e.g `focused-turing3`
func GetRandomName(retry int) string {

	// create a map to de-dupe on last name of players
	ln := make(map[string]string)
	for _, v := range packers {
		parts := strings.Split(v, ", ")
		if len(parts) > 0 {
			ln[parts[0]] = v
		}
	}

	right := make([]string, 0, len(ln))
	for k := range ln {
		right = append(right, strings.ToLower(k))
	}

	name := fmt.Sprintf("%s-%s", left[rand.Intn(len(left))], right[rand.Intn(len(right))])

	if retry > 0 {
		name = fmt.Sprintf("%s%d", name, rand.Intn(10))
	}
	return name
}
